---
# tasks file for packer
## OS Specific first
- include: install_Debian.yml
  when: ansible_facts['os_family'] == "Debian"

## General OSes
- name: install unzip
  package:
    name: unzip
    state: present
  become: yes
  when: ansible_facts['os_family'] != "Debian"

- name: download packer zip
  get_url:
    url: "{{ packer_zip_url }}"
    checksum: "sha256:{{ packer_sha256_url }}"
    dest: /tmp/packer.zip
  when: ansible_facts['os_family'] != "Debian"

- name: unpack packer
  unarchive:
    src: /tmp/packer.zip
    dest: /usr/local/bin
    copy: no
  become: yes
  when: ansible_facts['os_family'] != "Debian"

- name: remove packer zip
  file:
    path: /tmp/packer.zip
    state: absent
  when: ansible_facts['os_family'] != "Debian"
